# Generated by Django 4.1.3 on 2022-12-06 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_location_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='github',
            new_name='social_github',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='instagram',
            new_name='social_instagram',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='linkedin',
            new_name='social_linkedin',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='twitter',
            new_name='social_twitter',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='website',
            new_name='social_website',
        ),
    ]
