# Generated by Django 4.1.3 on 2022-12-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_github_profile_social_github_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created']},
        ),
    ]
